// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace BruSoft.VS2P4
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidVS2P4PkgString = "8358dd60-20b0-478a-83b8-ea8ae3ecdaa2";
        public static Guid guidVS2P4Pkg = new Guid(guidVS2P4PkgString);

        public const string guidVS2P4CmdSetString = "e64c92e7-8a32-4afd-af57-df9933b4e66d";
        public static Guid guidVS2P4CmdSet = new Guid(guidVS2P4CmdSetString);

        public const string guidSccProviderImagesString = "f24cc5f6-295f-4d3f-87e7-4ddc3a36af20";
        public static Guid guidSccProviderImages = new Guid(guidSccProviderImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int icmdCheckout = 0x0100;
        public const int icmdMarkForAdd = 0x0101;
        public const int icmdRevertIfUnchanged = 0x0102;
        public const int icmdRevert = 0x0103;
        public const int icmdGetLatestRevison = 0x0104;
        public const int icmdRevisionHistory = 0x0105;
        public const int icmdDiff = 0x0106;
        public const int icmdTimeLapse = 0x0107;
        public const int icmdRefresh = 0x0108;
        public const int icmdOpenInSwarm = 0x0109;
        public const int imnuFileSourceControlMenu = 0x0200;
        public const int imnuToolWindowToolbarMenu = 0x0201;
        public const int igrpFileSourceControl = 0x0300;
        public const int igrpSourceControlCommands = 0x0301;
        public const int igrpSccNowhere = 0x0304;
        public const int itbrSccToolbar = 0x0400;
        public const int igrpDocumentContextMenu = 0x0500;
        public const int iconCheckout = 0x0001;
        public const int iconMarkForAdd = 0x0002;
        public const int iconRevertIfUnchanged = 0x0003;
        public const int iconRevert = 0x0004;
        public const int iconGetLatestRevison = 0x0005;
        public const int iconRevisionHistory = 0x0006;
        public const int iconDiff = 0x0007;
        public const int iconTimeLapse = 0x0008;
        public const int iconRefresh = 0x0009;
        public const int iconOpenInSwarm = 0x000A;
    }
}