//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BruSoft.VS2P4 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BruSoft.VS2P4.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string _ {
            get {
                return ResourceManager.GetString(".", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VS2P4.
        /// </summary>
        internal static string _100 {
            get {
                return ResourceManager.GetString("100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This package provides access to Perforce source control..
        /// </summary>
        internal static string _101 {
            get {
                return ResourceManager.GetString("101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon _400 {
            get {
                object obj = ResourceManager.GetObject("400", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _500 {
            get {
                object obj = ResourceManager.GetObject("500", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _501 {
            get {
                object obj = ResourceManager.GetObject("501", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add File.
        /// </summary>
        internal static string Add_File {
            get {
                return ResourceManager.GetString("Add_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add {0} to Perforce?.
        /// </summary>
        internal static string Add_filename_to_Perforce {
            get {
                return ResourceManager.GetString("Add_filename_to_Perforce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddFiles.
        /// </summary>
        internal static string Add_Files {
            get {
                return ResourceManager.GetString("Add_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press OK to apply changes..
        /// </summary>
        internal static string ApplyProviderOptions {
            get {
                return ResourceManager.GetString("ApplyProviderOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t remove file {0} because it is checked out (opened for edit)..
        /// </summary>
        internal static string Cant_Remove_File_filename_Because_It_Is_Checked_Out {
            get {
                return ResourceManager.GetString("Cant_Remove_File_filename_Because_It_Is_Checked_Out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t rename file {0} because it must be checked out (opened for edit)..
        /// </summary>
        internal static string Cant_Rename_File_filename_Because_It_Must_Be_Checked_Out {
            get {
                return ResourceManager.GetString("Cant_Rename_File_filename_Because_It_Must_Be_Checked_Out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkout.
        /// </summary>
        internal static string Checkout {
            get {
                return ResourceManager.GetString("Checkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckoutFiles.
        /// </summary>
        internal static string Checkout_Files {
            get {
                return ResourceManager.GetString("Checkout_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to command is disabled. To change, go to Tools + Options + Source Control + VS2P4 Options..
        /// </summary>
        internal static string Command_Is_Disabled {
            get {
                return ResourceManager.GetString("Command_Is_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected to {0} as {1} and workspace {2}.
        /// </summary>
        internal static string Connected_To {
            get {
                return ResourceManager.GetString("Connected_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Failed.
        /// </summary>
        internal static string CONNECTION_FAILED {
            get {
                return ResourceManager.GetString("CONNECTION_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Succeeded.
        /// </summary>
        internal static string CONNECTION_SUCCEEDED {
            get {
                return ResourceManager.GetString("CONNECTION_SUCCEEDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteFiles.
        /// </summary>
        internal static string Delete_Files {
            get {
                return ResourceManager.GetString("Delete_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diff.
        /// </summary>
        internal static string Diff {
            get {
                return ResourceManager.GetString("Diff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: .
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetLatestRevision.
        /// </summary>
        internal static string Get_Latest_Revision {
            get {
                return ResourceManager.GetString("Get_Latest_Revision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information: .
        /// </summary>
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LockFiles.
        /// </summary>
        internal static string Lock_Files {
            get {
                return ResourceManager.GetString("Lock_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VS2P4.
        /// </summary>
        internal static string ProviderName {
            get {
                return ResourceManager.GetString("ProviderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file {0} you are trying to edit is read only on disk. Do you want do make the file writable so you can continue editing it?.
        /// </summary>
        internal static string QEQS_EditUncontrolledReadOnly {
            get {
                return ResourceManager.GetString("QEQS_EditUncontrolledReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file {0} you are trying to save is read only on disk. Do you want do make the file writable so it can be saved?.
        /// </summary>
        internal static string QEQS_SaveReadOnly {
            get {
                return ResourceManager.GetString("QEQS_SaveReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename File.
        /// </summary>
        internal static string Rename_File {
            get {
                return ResourceManager.GetString("Rename_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RenameFiles.
        /// </summary>
        internal static string Rename_Files {
            get {
                return ResourceManager.GetString("Rename_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RenameFile expects piped fileName, instead of: {0}.
        /// </summary>
        internal static string RenameFile_expects_piped_fileName {
            get {
                return ResourceManager.GetString("RenameFile_expects_piped_fileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revert.
        /// </summary>
        internal static string Revert {
            get {
                return ResourceManager.GetString("Revert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RevertFiles.
        /// </summary>
        internal static string Revert_Files {
            get {
                return ResourceManager.GetString("Revert_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RevertFilesIfUnchanged.
        /// </summary>
        internal static string Revert_Files_If_Unchanged {
            get {
                return ResourceManager.GetString("Revert_Files_If_Unchanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revert If Unchanged.
        /// </summary>
        internal static string Revert_If_Unchanged {
            get {
                return ResourceManager.GetString("Revert_If_Unchanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to revert (will lose changes to reverted files)?.
        /// </summary>
        internal static string revertPrompt {
            get {
                return ResourceManager.GetString("revertPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RevisionHistory.
        /// </summary>
        internal static string Revision_History {
            get {
                return ResourceManager.GetString("Revision_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running program {0} with arguments {1}.
        /// </summary>
        internal static string Running_program {
            get {
                return ResourceManager.GetString("Running_program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Latest Revision.
        /// </summary>
        internal static string s {
            get {
                return ResourceManager.GetString("s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SccGlyphs4 {
            get {
                object obj = ResourceManager.GetObject("SccGlyphs4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checked in head revision.
        /// </summary>
        internal static string State_CheckedInHeadRevision {
            get {
                return ResourceManager.GetString("State_CheckedInHeadRevision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checked in, not at head revision.
        /// </summary>
        internal static string State_CheckedInPreviousRevision {
            get {
                return ResourceManager.GetString("State_CheckedInPreviousRevision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted at the head revision.
        /// </summary>
        internal static string State_DeletedAtHeadRevision {
            get {
                return ResourceManager.GetString("State_DeletedAtHeadRevision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open for edit, locked.
        /// </summary>
        internal static string State_Locked {
            get {
                return ResourceManager.GetString("State_Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked by other user.
        /// </summary>
        internal static string State_LockedByOtherUser {
            get {
                return ResourceManager.GetString("State_LockedByOtherUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Needs to be resolved.
        /// </summary>
        internal static string State_NeedsResolved {
            get {
                return ResourceManager.GetString("State_NeedsResolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open, marked for add.
        /// </summary>
        internal static string State_OpenForAdd {
            get {
                return ResourceManager.GetString("State_OpenForAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open for branch.
        /// </summary>
        internal static string State_OpenForBranch {
            get {
                return ResourceManager.GetString("State_OpenForBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open, marked for delete.
        /// </summary>
        internal static string State_OpenForDelete {
            get {
                return ResourceManager.GetString("State_OpenForDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open, marked for delete by other user.
        /// </summary>
        internal static string State_OpenForDeleteOtherUser {
            get {
                return ResourceManager.GetString("State_OpenForDeleteOtherUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open for edit by you.
        /// </summary>
        internal static string State_OpenForEdit {
            get {
                return ResourceManager.GetString("State_OpenForEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open for edit, differs from head revision.
        /// </summary>
        internal static string State_OpenForEditDiffers {
            get {
                return ResourceManager.GetString("State_OpenForEditDiffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open for edit by other user.
        /// </summary>
        internal static string State_OpenForEditOtherUser {
            get {
                return ResourceManager.GetString("State_OpenForEditOtherUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open for integrate.
        /// </summary>
        internal static string State_OpenForIntegrate {
            get {
                return ResourceManager.GetString("State_OpenForIntegrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open, renamed, source marked for delete.
        /// </summary>
        internal static string State_OpenForRenameSource {
            get {
                return ResourceManager.GetString("State_OpenForRenameSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open, renamed, source marked for add.
        /// </summary>
        internal static string State_OpenForRenameTarget {
            get {
                return ResourceManager.GetString("State_OpenForRenameTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending add.
        /// </summary>
        internal static string Status_PendingAdd {
            get {
                return ResourceManager.GetString("Status_PendingAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TimeLapse.
        /// </summary>
        internal static string Time_Lapse {
            get {
                return ResourceManager.GetString("Time_Lapse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VS2P4 Tool Window.
        /// </summary>
        internal static string ToolWindowCaption {
            get {
                return ResourceManager.GetString("ToolWindowCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file {0} you are going to delete is a source controlled file. Are you sure you want to continue and delete this file?.
        /// </summary>
        internal static string TPD_DeleteControlledFile {
            get {
                return ResourceManager.GetString("TPD_DeleteControlledFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P4Service.Connect() ArgumentException unable to connect. Server {0}, Workspace {1}.
        /// </summary>
        internal static string Unable_To_Connect {
            get {
                return ResourceManager.GetString("Unable_To_Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Diff Report.
        /// </summary>
        internal static string View_Diff_Report {
            get {
                return ResourceManager.GetString("View_Diff_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Revision History Report.
        /// </summary>
        internal static string View_Revision_History_Report {
            get {
                return ResourceManager.GetString("View_Revision_History_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Time Lapse Report.
        /// </summary>
        internal static string View_Time_Lapse_Report {
            get {
                return ResourceManager.GetString("View_Time_Lapse_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VS2P4 Options.
        /// </summary>
        internal static string VS2P4_Options {
            get {
                return ResourceManager.GetString("VS2P4_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: .
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
